const List<String> AssetType = [
  'Air Compressor',
  'Air Knife',
  'Blender',
  'Classifier',
  'Drive-DC',
  'Extruder',
  'Filter-Bag',
  'Filter-Cartridge',
  'Forklift',
  'Gearbox',
  'Generator',
  'Hopper',
  'Metal Detector',
  'Meter-H2O',
  'Meter-NG',
  'Mixer',
  'Motor-AC',
  'Motor-DC',
  'Pelletizer',
  'Pump-Vacuum',
  'Relief Device-PSV',
  'Safety Shower',
  'Screw-Extruder',
  'Silo',
  'Tank',
  'Vehicle',
  'Vessel',
  'Waterbath',
];
